version: '3'
services:

  # you can exec into this container and probe the overlay net
  busy:
    image: busybox
    networks: [ frontend ]
    command:
      - sleep
      - '10000'
    deploy:
      placement:
        constraints:
          - node.hostname == moby

  stealthy:
    image: emilevauge/whoami
    networks: [ frontend ]
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: PathPrefix:/stealthy

  box:
    image: emilevauge/whoami
    networks: [ frontend ]
    # ports:
    #   - 800:80
    deploy:
      replicas: 3
      labels:
        traefik.port: 80
        traefik.frontend.rule: PathPrefix:/box

  traefik:
    image: traefik
    ports:
      - 80:80
      - 8080:8080
    networks: [ frontend ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --web
      - --logLevel=DEBUG
      - --docker
      - --docker.swarmmode
      # - --docker.watch
      # - --docker.domain=traefik
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  frontend: